### ISSUE TITLE
Add Link To Attached Script in Inspector For Nodes

### ISSUE THREAD

**Issue by Corysia** [BabylonJS/Editor#177] opened 2020-05-22 15:22 UTC
Experimenting with attaching a script to an object, I noticed I couldn't easily see the object had a script.  When opening the script, I could see it was attached to an object from the left-hand pane of the editor.  It would be nice to see and access scripts from the object via the inspector similar to how Unity and Unreal offer.

**Comment by julien-moreau** [comment] 2020-05-31 10:59
Hey ! Thanks for this feedback, I’m adding the link ASAP !

The V4 of the editor is being developed and should be released in few weeks. As this is issue is not a bug that breaks projects, i suggest to focus on the V4 and provide you a more rich exprerience on it.

Are you interested to be a beta tester of the V4 ?

**Comment by Corysia** [comment] 2020-05-31 16:38
Yes, I would be very interested in trying out v4 and seeing what I can do with it!

**Comment by julien-moreau** [comment] 2020-06-01 21:32
Good! Are you on the babylonjs forum?

**Comment by Corysia** [comment] 2020-06-02 02:13
Yes I am, same username.

**Comment by julien-moreau** [comment] 2020-06-24 11:29
Done, added a button to open the file directly from the inspector.
Also added (hidden by default) a preview section of the script like Unity does

**Closed by julien-moreau** 2020-06-24 11:29 UTC
Labels: enhancement
