### ISSUE TITLE
If you put the content created in editor on the web server, it will be very heavy and will not work on mobile devices.

### ISSUE THREAD

**Issue by udemegane** [BabylonJS/Editor#222] opened 2020-10-25 00:10 UTC
I created an "empty project" in babylonjs editor v4.0.0-beta8, built it, extracted the scenes folder, dist folder, index.html and cannon.js and put it on my home server and github pages.
https://udemegane.github.io/babylonjs-empty-project/ ...
Despite the fact that the scene is only a cube and floor, it only runs at about 20-30 FPS. On my smartphone, it just displayed a blank page. It's obviously heavier than the official example.
What is wrong with it?
Thank you.

**Comment by julien-moreau** [comment] 2020-10-25 00:51
Hey @udemegane !
Thanks for that feedback! By default the editor sets SSAO2 and motion blur on. This can explain the drop in FPS. In the editor select the scene then in the inspector -> rendering, disable SSAO and motion blur.

For the blank page, i think this is due to the usage of SSAO2 that is available only with WebGL2 compatible devices. I’m fixing to check if the device is supported before applying SSAO2

**Comment by udemegane** [comment] 2020-10-25 01:49
Thanks for the fast response!
As you pointed out, there was a significant improvement in fps by turning off ssao2 and motion blur.
However, even with ssao turned off, my iphone X displayed a blank page, and my webgl 2.0-enabled Android machine displayed a blank page as well. I still don't know why.

**Comment by julien-moreau** [comment] 2020-10-27 21:47
Hey i reproduced on my iPhone 11 and finally found: this is the usage of Cascaded Shadow Maps. You should turn off shadows (or at least add shadows without using the cascaded mode) to get it working on low end devices.

I think the editor should ask the target and activate/deactivate features. Do you have any idea how we should expose that feature in the editor?

**Comment by udemegane** [comment] 2020-10-29 20:10
It worked perfectly. Thank you so much for your efforts!
I think it's a good idea for editors to ask the user which target device they want to use when they create a project, and then the initial settings are made accordingly. For example, Unreal Engine 4.

**Comment by julien-moreau** [comment] 2020-11-21 13:54
Hey @udemegane, closing this issue, I create an issue focused on adding an interface to determine the rendering quality: https://github.com/BabylonJS/Editor/issues/227

**Closed by julien-moreau** 2020-11-21 13:54 UTC
