### ISSUE TITLE
npm i http-server@latest

### ISSUE THREAD

**Issue by kungfooman** [BabylonJS/Editor#207] opened 2020-08-09 10:38 UTC
Hello, you need to install the latest http-server, unless you want to run into this Windows only issue:

https://github.com/http-party/http-server/issues/525

```npm i http-server@latest```

`npm run webserver` won't load anything when clicking on the link in shell like `http://127.0.0.1:1338/`:

![image](https://user-images.githubusercontent.com/5236548/89730132-59efc480-da3c-11ea-944a-2a75d4b96a1a.png)

**Comment by julien-moreau** [comment] 2020-08-12 11:49
Hey @kungfooman nice catch!!!
Thanks for reporting, I just pushed the fix on the branch "release/4.0.0"

I haven't reproduced before because I always added "/index.html" in my URL -_-

**Closed** 2020-08-12 11:49 UTC
