### ISSUE TITLE
Can't build on Linux

### ISSUE THREAD

**Issue by lichotapia** [BabylonJS/Editor#18] opened 2017-04-27 09:04 UTC
Tried to build it in Linux, Centos7, but couldn't. I think there is a problem with the Electron dependency.
I attached the npm log for the master branch.
Tried both branches, none worked.
I'll try to build it on Windows.

Anyway, it's a great work you are doing!
I would like to add text in the scene, that would be excellent.

Thanks,
Lisandro Tapia
[npm-debug.txt](https://github.com/BabylonJS/Editor/files/961024/npm-debug.txt)

**Comment by julien-moreau** [comment] 2017-04-28 12:09
Thanks! I'm happy that you use the editor! :)
I'll find a solution for build on Linux and will focus on adding texts in scene
By adding text, I propose to create and edit dynamic textures you can apply on materials, is that ok for you ?

**Comment by lichotapia** [comment] 2017-05-05 08:09
Yes, that would be great. Thanks!

**Comment by julien-moreau** [comment] 2017-05-10 18:10
I cannot reproduce the linux error, I used node v7. What version are you using ?
For the dynamic textures editor, you can reach the preview link here : http://editor.babylonjs.com/preview/ and access the tool using Tools -> Dynamic Texture Builder :)

**Comment by julien-moreau** [comment] 2017-06-08 11:11
Any news ?

**Comment by lichotapia** [comment] 2017-06-09 09:12
Sorry, I'm using node 6.10.1. Is the last one on my distro,
I'll try to update and see how it goes. If not, I'll try on Windows.

Thanks!

**Comment by julien-moreau** [comment] 2017-06-09 11:04
Maybe the dependency doesn't work with this version of node :(

**Comment by julien-moreau** [comment] 2017-06-11 13:49
Then I close the issue, don't hesitate to reopen one if the problem persists, thanks!

**Closed by julien-moreau** 2017-06-11 13:49 UTC
